name: coreJS Documentation
encoding: utf-8

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://bq-devtools.github.io/corejs-doc/index.html'
author:         'bq'
